from fastapi import FastAPI, UploadFile, File
from fastapi.responses import JSONResponse
from database import conn, cursor
from fastapi.middleware.cors import CORSMiddleware
from ai import analyze_image
from pydantic import BaseModel
from typing import List, Optional
import shutil, json, os
from groq import Groq
from dotenv import load_dotenv

load_dotenv()
groq_client = Groq(api_key=os.getenv("GROQ_API_KEY", ""))

app = FastAPI()
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
def home():

    return {
        "status": "running",
        "message": "Radiology AI Backend Online"
    }


@app.post("/analyze")
async def analyze(file: UploadFile = File(...)):

    save_path = f"../uploads/{file.filename}"

    with open(save_path, "wb") as buffer:
        shutil.copyfileobj(
            file.file,
            buffer
        )

    result = analyze_image(save_path)

    try:

        result_json = json.loads(result)

        cursor.execute("""
        INSERT INTO reports
        (
            filename,
            findings,
            impression,
            confidence,
            recommendation
        )
        VALUES (?, ?, ?, ?, ?)
        """,
        (
            file.filename,
            result_json.get("findings", ""),
            result_json.get("impression", ""),
            result_json.get("confidence", 0),
            result_json.get("recommendation", "")
        ))

        conn.commit()

        return {
            "filename": file.filename,
            "analysis": result_json
        }

    except Exception as e:

        return {
            "filename": file.filename,
            "error": str(e),
            "raw_response": result
        }

class ChatMessage(BaseModel):
    role: str
    content: str

class AnalysisContext(BaseModel):
    impression: Optional[str] = None
    findings: Optional[str] = None
    confidence: Optional[int] = None
    recommendation: Optional[str] = None

class ChatRequest(BaseModel):
    messages: List[ChatMessage]
    analysis_context: Optional[AnalysisContext] = None


@app.post("/chat")
async def chat(req: ChatRequest):
    system_parts = [
        "You are an expert AI Radiology Assistant powered by Groq.",
        "Answer questions about radiology, medical imaging, findings, and diagnostic techniques clearly and accurately.",
        "Always remind users that AI analysis must be confirmed by a qualified radiologist.",
    ]
    ctx = req.analysis_context
    if ctx:
        system_parts.append("\n--- Current Radiology Analysis (generated by Gemini AI) ---")
        if ctx.impression:    system_parts.append(f"Clinical Impression: {ctx.impression}")
        if ctx.findings:      system_parts.append(f"Findings: {ctx.findings}")
        if ctx.confidence:    system_parts.append(f"Confidence: {ctx.confidence}%")
        if ctx.recommendation: system_parts.append(f"Recommendation: {ctx.recommendation}")
        system_parts.append("Reference these findings when answering questions about the current image.")

    groq_messages = [{"role": m.role, "content": m.content} for m in req.messages[-10:]]

    try:
        completion = groq_client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "system", "content": "\n".join(system_parts)}] + groq_messages,
            max_tokens=1024,
            temperature=0.7,
        )
        return {"reply": completion.choices[0].message.content}
    except Exception as e:
        return JSONResponse(status_code=500, content={"error": str(e)})
    
    
@app.get("/history")
def history():

    cursor.execute("""
    SELECT *
    FROM reports
    ORDER BY id DESC
    """)

    rows = cursor.fetchall()

    return rows
@app.get("/report/{report_id}")
def get_report(report_id: int):

    cursor.execute(
        "SELECT * FROM reports WHERE id=?",
        (report_id,)
    )

    report = cursor.fetchone()

    if report is None:
        return {"error": "Report not found"}

    return report
